name: CI

on:
  push:
    branches:
      - updated
  pull_request:
    branches:
      - updated

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      #- name: Build client
      #  run: npm run build --prefix client

      - name: Build server
        run: npm run build

      - name: List dist directory contents
        run: ls -R dist/public

      #- name: Run tests
      #  run: npm test

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/updated'
        uses: actions-gh-pages@v3
        with:
          github_token: ${{ secrets.secret }}
          publish_dir: dist/public
